### ISSUE TITLE
Absolute paths in .cfg file

### ISSUE THREAD

**Issue by soeren-sandal** [IARSystems/project-migration-tools#15]
When use "Select source folder..." and add a folder, the tool adds a line to the .cfg file like this:
`<selectedPath>C:\Sandbox\Demo-App\platform\common\bsp\devices\MY9221</selectedPath>`

It's an absolute path, which is problematic, because I want to share the project setup across my team.

I would like it to write a relative path like this instead:
`<selectedPath>$PROJ_DIR$\..\platform\common\bsp\devices\MY9221</selectedPath>`

I tried just writing this directly to the .cfg file, but then rescan doesn't add my new files or throw an error.

Am I doing something wrong?

Thanks

**Comment by felipe-iar** [comment]
At the moment the tool only can only process absolute path names in `<selectedPath>`.
Using `$PROJ_DIR$` is a good improvement suggestion for a future release. 

Thank you very much.
