### ISSUE TITLE
Reformats EWARM Project File when scanning files/folders

### ISSUE THREAD

**Issue by NotKasperNielsen** [IARSystems/project-migration-tools#19]
When I add a new folder to my repo and want to add it to my IAR EW project, I go to "Tools -> Select source folder ...".
This correctly finds the folder, adds it to the .cfg file and to the project.

The problem is that now my .ewp file has now been completely reformatted, with git detecting of thousands of changes. The file is still valid XML, but I have no chance of knowing what happened or backtracking in my history.
![image](https://github.com/IARSystems/project-migration-tools/assets/88884973/7d087659-d131-49a5-8771-e9cbabc2b251)

To restore order to chaos, I have to make a new change to the project options and save again in IAR EW. Usually I just exclude a file and then include it again. Now the file is back in the "correct" format, and I can see the few lines that actually changed.
![image](https://github.com/IARSystems/project-migration-tools/assets/88884973/51397c11-6171-4124-b3b0-776f89f6f522)

The same thing happens when I use "Tools -> Rescan Selected Source Folder...", even though nothing has actually changed.

I have an example of this here:
https://github.com/NotKasperNielsen/STM32-G4-EWPtool-Example/tree/EWP_file_reformatting_example

**Comment by felipe-iar** [comment]
Hi @NotKasperNielsen ,

Once generated/rescanned, please try always saving the `.ewp` project again from within the Embedded Workbench IDE, after you reload it from disk and before committing to git version control. This procedure should reduce the chaos, by reparse the XML keys in accordance with the exact format which the current IDE version is actually using.

Let me know if this procedure helps.

**Comment by felipe-iar** [comment]
I see now that you are already doing it. Apologies for the rushy reply. The EWPtool uses a different XML parser from the one used in the actual product. I work on a patch to reduce the chaos programatically. Please hold on.

**Comment by NotKasperNielsen** [comment]
No worries... Thanks for picking this up!
