### ISSUE TITLE
Which version of Keil uVision is possible to convert.

### ISSUE THREAD

**Issue by jae102** [IARSystems/project-migration-tools#2]
Hi,

Actually, I can see V5.x is available to convert. 
But, I am using V4.53.0.6.

So, I would like to know V4.x is possible to convert for now.

Thanks in advance,
BRs.

Tommy JY Lee

**Comment by blueentity** [comment]
I agree - README.md should mention the minimum requirements to use the tool including minimum compatible versions of the various Embedded Workbench editions.

**Comment by felipe-iar** [comment]
Hi @jae102 and @blueentity,

Thanks for your question and valuable feedback. 

We will start working on updates which will cover these as well as other questions on the README.
I will leave this issue open until we merge so you will get a notification.
Stay tuned.

Best regards.
