### ISSUE TITLE
Fails to recognize some paths and corrupts include-path.

### ISSUE THREAD

**Issue by NotKasperNielsen** [IARSystems/project-migration-tools#21]
After updating to v4.1.8 EWP-Tool makes weird changes to the include-path sections of my `.ewp`.
It deletes lots of lines. Initially it looked like it did not recognize folders below the level you select in the interface, but on closer inspection that was not the case.

I had a hard time reproducing it in a minimal example, but in the end I succeeded. I can't tell you the exact failure mode, but it has something to do with folder name lengths and/or path depth and the order they are listed in the `.cfg` file.

See my example here: https://github.com/NotKasperNielsen/STM32-G4-EWPtool-Example
Branch: v4.1.8_Missing_Subfolders

**Comment by felipe-iar** [comment]
Hi @NotKasperNielsen. Apologies for the seamlessly introduced issue and thanks for taking time to prepare the test case. I would like to take a look. However, I am currently unable access the sample at the STM32-G4... private repo when using my (@felipe-iar) account.
