### ISSUE TITLE
’-'/minus character is not supported in the selceted source folder name

### ISSUE THREAD

**Issue by joe-ju** [IARSystems/project-migration-tools#35]

**Comment by joe-ju** [comment]
After further testing, it's a bug that this tool doesn't support the name of folder name inovlving '-'/minus when selecting source folder.

**Comment by felipe-iar** [comment]
Thanks for testing EWPtool, @joe-ju.

Although I was unable to reproduce the issue as described. Could you please share the items below?
- the original `PROJ_FNAME.ewp` file in which the issue has been seen (before modified by EWPtool)
- the `PROJ_DIR/settings/PROJ_FNAME.log` file created after EWPtool runs?

While editing an issue here on GitHub, you can drag and drop the files...

![image](https://github.com/IARSystems/project-migration-tools/assets/54443595/d87c74bc-c535-4679-961b-1473f1850514)

**Comment by joe-ju** [comment]
@felipe-iar please check the attachments. Here I appended the .log suffix to .ewp file to make this file could be permitted to upload.
[mytest.log](https://github.com/IARSystems/project-migration-tools/files/12655067/mytest.log)
[mytest.ewp.log](https://github.com/IARSystems/project-migration-tools/files/12655090/mytest.ewp.log)

**Comment by felipe-iar** [comment]
@joe-ju Thanks for providing the requested files in such a clever way.

If my assertions were correct, I able to pinpoint one potential culprit in the selection dialog then the path contains a blank space. Please try this manual workaround:

* Open the `$PROJ_DIR$\settings\mytest.ewp` and manually set it to
```xml
<?xml version="1.0"?>
<EWPtool>
  <selectedPath>$PROJ_DIR$\APL_A01_New MAC-PHY_TPM</selectedPath>
</EWPtool>
```
* Choose __Tools__>__Rescan selected source folder(s)__

* Let me know if that works from your end.

**Comment by joe-ju** [comment]
@felipe-iar I removed the original space from the folder name and recreated a new project, but unfortunately, it still doesn't work.
[mytest.ewp.log](https://github.com/IARSystems/project-migration-tools/files/12667555/mytest.ewp.log)
[mytest.log](https://github.com/IARSystems/project-migration-tools/files/12667557/mytest.log)

**Comment by felipe-iar** [comment]
@joe-ju Thanks for the feedback. Though it is bad news. I am sorry to hear that and apologize for the issue you are facing.

I tried to reproduce the issue based on the information provided so far, using the workaround. I got the sources detected. I am sharing this project with you here ([test-35.dir.zip](https://github.com/IARSystems/project-migration-tools/files/12671956/test-35.dir.zip)). If possible, please try the following:
1. Extract the archive into a suitable location, open the project and see the sources/preprocessor were detected.
2. Close the workspace and create a new empty project that overwrites test-35.ewp
3. Select the __Tools__>__Rescan selected folder(s)__ menu command. 

And let me know if that works.

> __Note__ for now, do not use the menu comamnd "Select source folder".

**Comment by felipe-iar** [comment]
Hi @joe-ju. A new version has been released. Please test your project with the new project and let me know how it goes. https://github.com/IARSystems/project-migration-tools/releases/latest
