### ISSUE TITLE
v4.2.4 currupts .ewp after "rescan"

### ISSUE THREAD

**Issue by NotKasperNielsen** [IARSystems/project-migration-tools#44]
When running "Rescan selected source folders(s)" EWARM is unable to re-load the project `.ewp`
![image](https://github.com/IARSystems/project-migration-tools/assets/88884973/db5448af-dc04-4d63-8b0b-185f2f1bb445)

When looking at the git diff you can see that the opening tag for `<buildActions>` and `<buildAction>` are deleted.
Also, it still adds extra `&amp;` in the `<cmdline>` lines.
![image](https://github.com/IARSystems/project-migration-tools/assets/88884973/1cfe4aea-c7a5-4748-b807-64c55ec435b7)

**Comment by felipe-iar** [comment]
Thanks for reporting this issue, @NotKasperNielsen. Can you mention which IDE version or product version was in use?

**Comment by NotKasperNielsen** [comment]
This was with EWARM 9.40.2

**Comment by felipe-iar** [comment]
This was fixed on Release 4.2.5. Please upgrade and test.

**Comment by NotKasperNielsen** [comment]
v4.2.5 fixes the original project corruption issue, but it still has issues around the > symbol `&gt;`
![image](https://github.com/IARSystems/project-migration-tools/assets/88884973/da9a91b6-170d-4fe3-8de8-6bcd260c43d7)

This was inserted into my `.ewp` when auto-migrating from build-scripts to build-actions.

If i just cleanup the command an remove the extra stuff the migration added, I don't have any issues.
![image](https://github.com/IARSystems/project-migration-tools/assets/88884973/efd8fecb-13c7-44e3-a655-0cf061666e62)

**Comment by felipe-iar** [comment]
Thanks. These are treated individually. I am working on a new fix to cover more use cases in which EWPtool processes pipes and redirectors accordingly.
![image](https://github.com/IARSystems/project-migration-tools/assets/54443595/527af724-8163-4e33-b1c0-d11ce15751c1)
Would that work for your use case?

**Comment by NotKasperNielsen** [comment]
I don't actually need pipes for my build actions, so after updating my `.ewp` v4.2.5 is working for me.

**Comment by felipe-iar** [comment]
Thanks. Either way I will soon release 4.2.6 with support for the extra redirectors, just in case they are also needed in the future.
