### ISSUE TITLE
Using EWPtool to import source files into IAR Embedded Workbench, when building, it shows that all. c files cannot be opened

### ISSUE THREAD

**Issue by zzcoisini** [IARSystems/project-migration-tools#49]
![image](https://github.com/IARSystems/project-migration-tools/assets/107633546/7d7bcea6-0144-4eb6-8166-fc741c040313)

**Comment by felipe-iar** [comment]
Thanks for using IAR EWPtool, @zzcoisini 

Although I was unable to reproduce the issue as described. Could you please share the items below?
- the original `PROJ_FNAME.ewp` file in which the issue has been seen (before modified by EWPtool)
- the `PROJ_DIR/settings/PROJ_FNAME.log` file created after EWPtool runs?

While editing an issue here on GitHub, you can drag and drop the files...

![image](https://github.com/IARSystems/project-migration-tools/assets/54443595/eb200031-e7d5-49ab-8ae7-37fba22f8b97)

**Comment by felipe-iar** [comment]
Hi. If you need further support on this, please request IAR technical support
https://www.iar.com/knowledge/support/request-technical-support
