### ISSUE TITLE
Issue with automatic source detection

### ISSUE THREAD

**Issue by sharpgeek** [IARSystems/project-migration-tools#5]
I found a couple of issues with the EWP tool in which I need some help.

- I noticed that the it does not detect *.asm and *.s51 assembly source files. Even if I have to migrate the Assembly source code on these files, I would like to have my project populated with them, since dozens of files are involved.

- I noticed that the tool also populates the project with *.a libraries. This is counterproductive as pre-compiled libraries aren't really source code. I understand that adding a library as a node in the source tree will work when building the project. But I rather prefer to have the libraries set manually. There were several cases in which I had to remove many libraries which were unsuitable for the Release configuration and vice-versa.

I am using EW8051 version 10.40.1, which has the "Project Connection" feature available.

Thx.

**Comment by felipe-iar** [comment]
Hi @sharpgeek,

Thank you for this great feedback. 
It is true that the architectures relying on the XLINK technology use different extensions for their assembly source files.

We plan to add support for more extensions soon on the next release so you can benefit from it. 
We will take your requests into consideration.

I will leave this ticket open so you can get a notification when we merge the related update.
Stay tuned.

Best regards.
