### ISSUE TITLE
Add automatic reload feature or add a reload button

### ISSUE THREAD

**Issue by AlexandreMarkus** [IARSystems/project-migration-tools#7]
I would like the tool to reload automatically (or manually with a reload button) all sources files and preprocessor includes, when there is a change on the drive. 

Automatic reload should occur when: 
- Changing directory name
- Changing file name
- Adding a file
- Removing a file

It would also be helpful to remove (replace) old preprocessor includes

**Comment by felipe-iar** [comment]
Thanks for your suggestion, @AlexandreMarkus. 

It is an interesting use case. The EWPtool was initially designed as a sidekick for when populating a project tree during a migration process to the IAR Embedded Workbench IDE. At that point, we didn't envision continued use of the tool.

From the IDE standpoint, it is an external tool that creates an IAR Project Connection (`.ipcf`) and, for convenience, performs a single modification to the opened `.ewp` project, by adding the reference to the project connection file, if it does not exist.

Except for the (potentially) touched part of the `.ewp`, the IDE has no awareness of what the EWPtool actually does.

According to your request, we can prepare a pre-release version which would cover updating the `.ipcf`, in accordance with the _previously chosen source folder_ (typically the project's top-level), when the external tool is triggered. Although, the IDE will not trigger an external tool without explicit user request. With that said, it would be possible to add an extra menu entry for it, so it would be possible to assign any available key binding for when refreshing the existing `.ipcf` source tree upon request. 

Would that work for you?

**Comment by AlexandreMarkus** [comment]
> Thanks for your suggestion, @AlexandreMarkus.
> 
> It is an interesting use case. The EWPtool was initially designed as a sidekick for when populating a project tree during a migration process to the IAR Embedded Workbench IDE. At that point, we didn't envision continued use of the tool.
> 
> From the IDE standpoint, it is an external tool that creates an IAR Project Connection (`.ipcf`) and, for convenience, performs a single modification to the opened `.ewp` project, by adding the reference to the project connection file, if it does not exist.
> 
> Except for the (potentially) touched part of the `.ewp`, the IDE has no awareness of what the EWPtool actually does.
> 
> According to your request, we can prepare a pre-release version which would cover updating the `.ipcf`, in accordance with the _previously chosen source folder_ (typically the project's top-level), when the external tool is triggered. Although, the IDE will not trigger an external tool without explicit user request. With that said, it would be possible to add an extra menu entry for it, so it would be possible to assign any available key binding for when refreshing the existing `.ipcf` source tree upon request.
> 
> Would that work for you?

Yes, that would work for me, thank you!
Would it be possible to clean old (modified) preprocess includes from the configuration?
Would it be possible to add a custom iarProjectConnection name field, that would not be overwritten by a refresh?
suggestion: the name field could be use as custom name and a source field could be use as the actual folder path. 
```xml
<iarProjectConnection name="Application\MyCustomName\Components" source="src" oneShot="false">
```
Would it be possible to add a custom group name field, that would not be overwritten by a refresh?
suggestion: the name field could be use as custom name and a source field could be use as the actual folder path. 
```xml
<group name="Component1\Sources" source="..\src\Components\Component1\Sources">
```

Thank you!

**Comment by felipe-iar** [comment]
The [EWPtool 3.3.0](https://github.com/IARSystems/project-migration-tools/releases/tag/3.3.0) is now available for testing. 🧪 

Here comes some extra bits of information that might prove to be useful:
* Folders which had all headers removed should now be removed upon source tree re-scanning.

* The current _groups naming convention_ is mirrored on the actual source tree structure. Right now, customizations to the `.ewp` become possible, once the `.ipcf` file is removed from the project.

We are counting on your feedback. Please enjoy. And thanks in advance.

**Comment by AlexandreMarkus** [comment]
Good job, I did find some room of improvement:

The old preprocess configuration include has not been removed. In the following picture, if I replace v102 with v103, I would like the preprocess to replace the old one.
![image](https://user-images.githubusercontent.com/59664238/148980692-2ee6fb26-989c-4f26-87cf-158d1f2540e1.png)

>The current groups naming convention is mirrored on the actual source tree structure. Right now, customizations to the .ewp become possible, once the .ipcf file is removed from the project.

Would be very useful to be able to add custom group names as suggested previously, because if I remove the .ipcf file to do a customization, I would not be able to rescan again...

**Comment by felipe-iar** [comment]
Thank you for your swift feedback.

From my end, I investigated what could be possibly going on in v3.3.0. Then I realized:

* The `.ipcf` generated by the __EWPtool__ was correctly reflecting the changes made to a source tree similar to yours, meaning that whenever a header folder is deleted or renamed, the regenerated `.ipcf` should be updated accordingly.
* There is a catch: once any setting coming from the `.ipcf` are saved to the `.ewp` project, those become leftovers in the case where they are removed from the `.ipcf`. :bulb: For v3.3.0, a possible workaround would be to remove all the _Additional include directories_ and let the `.ipcf` repopulate the field in accordance with the filesystem current state.

Leaving the _group naming customizations_ aside at this point of our discussion (we can go back to that next):
We discussed the hypothesis of completely getting rid of the `.ipcf` as the middle-man, towards better usability. It always was the core purpose of the tool, since its beginning. Please hold-on and stay tuned while we prepare EWPtool v4.0.0. ☕

**Comment by felipe-iar** [comment]
The [EWPtool 4.0.0](https://github.com/IARSystems/project-migration-tools/releases/tag/4.0.0) is now available for testing. 🧪 

We are counting on your feedback. Please enjoy. And thanks in advance.

**Comment by felipe-iar** [comment]
Please disregard v4.0.0. Instead, if possible, try v4.1.0.
The newest fixes minor glitches while providing better handling for project's customizations, directly from the IDE.
The README.md file was also updated to reflect the changes and contains some important information as well.
Currently it can be found on its own branch: https://github.com/IARSystems/project-migration-tools/tree/4.1.0
Thanks in advance.

**Comment by AlexandreMarkus** [comment]
> Please disregard v4.0.0. Instead, if possible, try v4.1.0. The newest fixes minor glitches while providing better handling for project's customizations, directly from the IDE. The README.md file was also updated to reflect the changes and contains some important information as well. Currently it can be found on its own branch: https://github.com/IARSystems/project-migration-tools/tree/4.1.0 Thanks in advance.

Thank you, I will test it and give you my feedback

**Comment by AlexandreMarkus** [comment]
Thank you for your good work. 
On the release v4.1.0 I did notice that the preprocessor includes section is now updating itself 💯, but it seems to have deleted all previous (other) includes that were in the list. Would it be possible to keep the other Includes also? The rescan button is updating files according to the local folder very well in this release!
I'm also looking forward to test that issue #8 when it will be released👍

**Comment by felipe-iar** [comment]
Thank you for your great help so far on testing the new features.
We've updated the EWPtool to v4.1.1. After the major changes, there are only minor but relevant changes.

It is available here: https://github.com/IARSystems/project-migration-tools/releases/tag/4.1.1
Hopefully the major problems are gone now and v4.1.1 became the best version currently in existence.
Even then, please let us know if you find something.

Thanks in advance.

**Comment by AlexandreMarkus** [comment]
Thank you for your work, I will try to show you some of my observations with an example:

Here is my project
![image](https://user-images.githubusercontent.com/59664238/150171192-90c3b7ae-8032-4664-8f9a-b5bc45f49f09.png)

Now I want to add a new library
![image](https://user-images.githubusercontent.com/59664238/150171731-b19412ea-fb7d-4c68-b665-94bf269d2113.png)

Now I want to move the library to a different  group
![image](https://user-images.githubusercontent.com/59664238/150172100-95dc7be1-e3a8-4cf0-bf4d-0265fa823785.png)

Here are the issues if I do some modification in the file explorer, then do a Rescan selected source folder...
| Add new file to the same library    | Update library to new version|
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/59664238/150172985-e1c8e2bf-0522-4990-bc54-5ed34f165826.png)     | ![image](https://user-images.githubusercontent.com/59664238/150173256-cb64d549-fdb6-46fd-9db5-4f70f9d461fb.png)      |

Here are the results I would expect after clicking on Rescan selected source folder...
| Add new file to the same library    | Update library to new version|
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/59664238/150174053-0f558722-36e7-4107-b725-6ccebc371066.png)    | ![image](https://user-images.githubusercontent.com/59664238/150173618-34391d5a-3c0a-4150-9168-8083502a3339.png)     |

Thank you!

**Comment by felipe-iar** [comment]
Thanks for the detailed description.

The newest pre-release can be found here:
https://github.com/IARSystems/project-migration-tools/releases/tag/4.1.2

Now it can scan new files added to __a previously added folder__, while respecting the group customization.

Although, upon re-scan, EWPtool will always first look at the filesystem current state.
If a folder was previously added as `v1.0.0` and later renamed to `v1.0.1` in the filesystem, then EWPtool will detect that `v1.0.0` was removed and that there is a new folder `v1.0.1` that was added.

Also, new sub-folders to previously existing folders are going to be treated as new (falling into the default/reflected groups within the `.ewp`) until they are customized.

PS: For adding a single file, or a single folder, the standard IDE option might be sufficient. EWPtool was designed to help with multiple folders at once.

Please let us know if this could work for you.

**Comment by AlexandreMarkus** [comment]
Thank you for your work and the explanation!

I do have an issue with files that were added manually. 

If I have the following project and libraryB was added manually(Add Files...).
![image](https://user-images.githubusercontent.com/59664238/151184973-ecd49e72-ae9b-4627-a95d-352ecf7c02f5.png)

 When I add the libraryA from the "Select source folder ...", it will remove files that were added manually. 
Here is the output:
![image](https://user-images.githubusercontent.com/59664238/151185369-7baea305-fcfd-4879-b9e7-858fb2059db5.png)

PS: You did mention there is a way to add a single file or a single folder. For adding a single folder, do you mean selecting all files from a folder? Otherwise, how do you manage to add a single folder, I do not find that option.

Thank you!!

**Comment by felipe-iar** [comment]
Thank you for your continuous feedback on our small sidekick tool.

A new release fix this bug.
https://github.com/IARSystems/project-migration-tools/releases/tag/4.1.3

The tool was removing file nodes related to non-monitored folders. Now it will only cleanup the monitored folders.

We're getting there. Please let us know if the latest version works for you.


>:bulb: PS: What I meant earlier by "adding a single folder at a time" was the Workspace context menu. Normally a single group would be created using `Add` > `Add Group...` followed by `Add` > `Add Files...`. the "Add Files..." dialog allows multiple selection as in standard Windows applications (by holding <kbd>CTRL</kbd> and clicking on each desired file, or else by holding <kbd>SHIFT</kbd> and clicking on the first, followed by the last to select multiple files). Dragging'n dropping a selection made from Windows Explorer into a chosen group also works on the latest versions of the IDE. You probably performed similarly for the `libraryB/Sources` group in the earlier comment. This is a default feature built into the IDE and has connection to the EWPtool.

**Comment by AlexandreMarkus** [comment]
Thank you for your work!

I know that 
> Now it can scan new files added to a previously added folder, while respecting the group customization.

I would like the tool to scan removed files deleted to a previously added folder, while respecting the group customization.

Also, the manually added preprocess includes seems to be deleted when I click Rescan, with the latest release.

Thank you!

**Comment by felipe-iar** [comment]
Thank you for providing further feedback.

A new release fixes this bug.
https://github.com/IARSystems/project-migration-tools/releases/tag/4.1.4

The tool was touching all the nodes for header folders unrelated to the selected folders.
From now on, upon selection/rescanning, it should be restricted to only sync the entries related to the selected folders. 
Any custom user entries to the header folders pointing to __outside__ the selected folders should be kept for manual maintenance.

Please let us know if the latest version worked for you.
