### ISSUE TITLE
Feature request: allow group name customization when using the EWPtool

### ISSUE THREAD

**Issue by felipe-iar** [IARSystems/project-migration-tools#8]
Some users might be using the EWPtool continuously, beyond the point of initial project populating the project.
Reference: #7 -- [comment](https://github.com/IARSystems/project-migration-tools/issues/7#issuecomment-1010013843).

For such reason, _group name_ customization when using __EWPtool__ continuously would be a nice possibility towards better usability.

**Comment by AlexandreMarkus** [comment]
@felipe-iar Very nice I will test it today
